import type { Playbook, PlaybookStep } from './types'

function step(
  id: string, order: number, title: string, description: string,
  commands: string[], notes: string,
  stepType: PlaybookStep['stepType'] = 'command'
): PlaybookStep {
  return {
    id, order, title, description, category: 'enum',
    commands, notes, required: true, stepType,
  }
}

const NOW = '2025-01-01T00:00:00.000Z'

function pb(
  id: string, name: string, description: string, tags: string[],
  steps: PlaybookStep[]
): Playbook {
  return {
    id, name, description, category: 'ccna',
    tags: ['ccna', 'cisco', ...tags], version: '1.0',
    createdAt: NOW, updatedAt: NOW, isBuiltIn: true, steps,
  }
}

export const BUILTIN_CCNA_B: Playbook[] = [

  pb('ccna-stp', 'STP Root Bridge Election',
    'Influence Spanning Tree Protocol root bridge placement using priority values.',
    ['stp', 'switching'],
    [
      step('stp-1', 1, 'Check Current Root Bridge',
        'Identify the current root bridge before making changes.',
        ['show spanning-tree', 'show spanning-tree vlan 1'],
        'The root bridge shows "This bridge is the root." All others show root MAC and priority.'),
      step('stp-2', 2, 'Set Root Bridge Priority',
        'Lower the priority on the intended root bridge.',
        ['spanning-tree vlan 1 priority 4096', 'spanning-tree vlan 10 priority 4096'],
        'Default priority is 32768. Must be a multiple of 4096. Lowest priority wins.'),
      step('stp-3', 3, 'Set Alternate Root Priority',
        'Configure a secondary/backup root bridge.',
        ['spanning-tree vlan 1 priority 8192'],
        'This switch will become root if the primary root fails.'),
      step('stp-4', 4, 'Enable PortFast on Access Ports',
        'Skip STP listening/learning on host-facing ports.',
        ['interface range FastEthernet0/1 - 24', 'spanning-tree portfast'],
        'PortFast skips the 30-second delay. Only use on ports connected to end devices.'),
      step('stp-5', 5, 'Verify Root Bridge',
        'Confirm the intended switch is now the root bridge.',
        ['show spanning-tree', 'show spanning-tree detail', 'show spanning-tree blockedports'],
        'Root bridge should show your switch. Blocked ports prevent loops.', 'verification'),
    ]),

  pb('ccna-etherchannel', 'EtherChannel (LACP)',
    'Bundle multiple physical links into one logical EtherChannel using LACP.',
    ['etherchannel', 'lacp'],
    [
      step('etch-1', 1, 'Verify Interface Consistency',
        'Confirm bundled interfaces have identical speed, duplex, and VLAN config.',
        ['show interfaces FastEthernet0/1', 'show interfaces FastEthernet0/2'],
        'Mismatched interfaces will prevent EtherChannel formation.'),
      step('etch-2', 2, 'Configure EtherChannel',
        'Group interfaces into a channel-group using LACP active mode.',
        ['interface range FastEthernet0/1 - 2', 'channel-group 1 mode active', 'exit'],
        'Active mode initiates LACP negotiation. Passive waits for the other side.'),
      step('etch-3', 3, 'Configure Port-Channel Interface',
        'Set trunk mode and allowed VLANs on the logical port-channel.',
        ['interface Port-channel 1', 'switchport mode trunk', 'switchport trunk allowed vlan all', 'no shutdown'],
        'Configuration on port-channel is inherited by member interfaces.'),
      step('etch-4', 4, 'Verify EtherChannel',
        'Check the channel group is up and bundled correctly.',
        ['show etherchannel summary', 'show etherchannel 1 port-channel', 'show interfaces Port-channel1'],
        'SU flags = Layer2, in use. P flag = port in bundle.', 'verification'),
    ]),

  pb('ccna-port-security', 'Port Security',
    'Restrict switch port access to specific MAC addresses to prevent unauthorized connections.',
    ['port-security', 'security'],
    [
      step('psec-1', 1, 'Enable Port Security on Access Port',
        'Switch port must be in access mode before enabling port security.',
        ['interface FastEthernet0/1', 'switchport mode access', 'switchport port-security'],
        'Port security only works on access ports, not dynamic ports.'),
      step('psec-2', 2, 'Set Maximum MAC Addresses',
        'Limit how many MAC addresses can be learned on the port.',
        ['switchport port-security maximum 2'],
        'Default is 1. Set to match the expected number of devices on the segment.'),
      step('psec-3', 3, 'Configure Sticky MAC Learning',
        'Dynamically learn and lock allowed MAC addresses.',
        ['switchport port-security mac-address sticky'],
        'Sticky learning persists learned MACs to running-config. Save with copy run start.'),
      step('psec-4', 4, 'Set Violation Mode',
        'Define how the switch reacts when a violation occurs.',
        ['switchport port-security violation restrict'],
        'Restrict: drops frames, increments counter. Shutdown: err-disables port. Protect: drops silently.'),
      step('psec-5', 5, 'Verify Port Security',
        'Review port security settings and any violations recorded.',
        ['show port-security interface FastEthernet0/1', 'show port-security address'],
        'Verify max, current, and violation counts. Err-disabled ports need manual recovery.', 'verification'),
    ]),

  pb('ccna-ipv6-static', 'IPv6 Static Routing',
    'Configure IPv6 addressing and static routes between routers.',
    ['ipv6', 'routing'],
    [
      step('ipv6-1', 1, 'Enable IPv6 Routing',
        'Enable IPv6 unicast routing globally on the router.',
        ['ipv6 unicast-routing'],
        'Required before any IPv6 routing will work. Not enabled by default.'),
      step('ipv6-2', 2, 'Assign IPv6 Addresses',
        'Configure link-local and global unicast addresses.',
        ['interface GigabitEthernet0/0', 'ipv6 address 2001:db8:1::1/64', 'ipv6 enable', 'no shutdown'],
        'ipv6 enable auto-generates a link-local address. Global address for routing.'),
      step('ipv6-3', 3, 'Add Static IPv6 Route',
        'Configure static routes pointing to the next-hop IPv6 address.',
        ['ipv6 route 2001:db8:2::/64 2001:db8:1::2', 'ipv6 route ::/0 2001:db8:1::2'],
        '::/0 is the IPv6 default route. Use global or link-local as next hop.'),
      step('ipv6-4', 4, 'Verify IPv6 Routes',
        'Check IPv6 routing table for static routes.',
        ['show ipv6 route', 'show ipv6 route static', 'show ipv6 interface brief'],
        'S routes = static. Via shows next-hop address and egress interface.', 'verification'),
      step('ipv6-5', 5, 'Test IPv6 Connectivity',
        'Ping across IPv6 static routes to verify forwarding.',
        ['ping ipv6 2001:db8:2::1', 'traceroute ipv6 2001:db8:2::1'],
        'Use ping ipv6 for IPv6 connectivity tests.', 'verification'),
    ]),

  pb('ccna-hsrp', 'HSRP (Hot Standby Router Protocol)',
    'Configure HSRP on two routers to provide gateway redundancy for LAN hosts.',
    ['hsrp', 'redundancy'],
    [
      step('hsrp-1', 1, 'Configure Active Router',
        'Set up HSRP on the primary router with higher priority.',
        ['interface GigabitEthernet0/0', 'ip address 192.168.1.2 255.255.255.0', 'standby 1 ip 192.168.1.1', 'standby 1 priority 110', 'standby 1 preempt', 'no shutdown'],
        'Virtual IP (192.168.1.1) is the gateway hosts use. Priority > 100 wins active role.'),
      step('hsrp-2', 2, 'Configure Standby Router',
        'Configure HSRP on the backup router with lower priority.',
        ['interface GigabitEthernet0/0', 'ip address 192.168.1.3 255.255.255.0', 'standby 1 ip 192.168.1.1', 'standby 1 priority 90', 'no shutdown'],
        'Standby router takes over if the active router fails.'),
      step('hsrp-3', 3, 'Configure HSRP Tracking',
        'Track the upstream interface to trigger failover if WAN link fails.',
        ['standby 1 track GigabitEthernet0/1 20'],
        'Decrement priority by 20 if tracked interface goes down.'),
      step('hsrp-4', 4, 'Verify HSRP Status',
        'Check which router is active and the virtual IP is correct.',
        ['show standby', 'show standby brief'],
        'Active router shows State = Active. Standby shows State = Standby.', 'verification'),
      step('hsrp-5', 5, 'Test Failover',
        'Simulate active router failure and verify standby takes over.',
        ['shutdown', 'show standby'],
        'Shutdown the active router interface and verify the standby becomes active.', 'verification'),
    ]),

  pb('ccna-dhcp-relay', 'DHCP Relay Agent',
    'Configure a router to forward DHCP requests to a remote DHCP server.',
    ['dhcp', 'helper-address'],
    [
      step('relay-1', 1, 'Configure Helper Address',
        'Point the client-facing interface to the DHCP server IP.',
        ['interface GigabitEthernet0/0', 'ip helper-address 10.0.0.10', 'exit'],
        'ip helper-address forwards UDP broadcast packets (DHCP) to the specified server.'),
      step('relay-2', 2, 'Verify DHCP Relay Operation',
        'Check that the router is forwarding DHCP requests.',
        ['show ip interface GigabitEthernet0/0', 'debug ip dhcp server packet'],
        'Helper address should appear in show ip interface output.', 'verification'),
      step('relay-3', 3, 'Test Client Address Assignment',
        'Verify a client behind the relay receives an IP from the remote server.',
        ['show ip dhcp binding', 'ping 10.0.0.10'],
        'Client should receive an IP from the remote server pool.', 'verification'),
    ]),

  pb('ccna-ospf-multiarea', 'OSPF Multi-Area',
    'Configure OSPF with multiple areas and verify ABR summarization.',
    ['ospf', 'routing', 'multiarea'],
    [
      step('mospf-1', 1, 'Configure Area 0 (Backbone)',
        'Configure the backbone OSPF area on the Area Border Router (ABR).',
        ['router ospf 1', 'network 10.0.0.0 0.0.0.255 area 0'],
        'All non-backbone areas must connect to area 0 through an ABR.'),
      step('mospf-2', 2, 'Configure Area 1',
        'Add networks in area 1 on the ABR and internal routers.',
        ['router ospf 1', 'network 192.168.1.0 0.0.0.255 area 1'],
        'Internal routers in area 1 only need area 1 network statements.'),
      step('mospf-3', 3, 'Configure ABR Summarization',
        'Summarize area routes at the ABR to reduce LSA flooding.',
        ['router ospf 1', 'area 1 range 192.168.0.0 255.255.0.0'],
        'Summarization reduces routing table size and LSA propagation.'),
      step('mospf-4', 4, 'Verify OSPF Areas',
        'Check OSPF neighbor table and area assignments.',
        ['show ip ospf', 'show ip ospf database', 'show ip ospf border-routers'],
        'ABR shows in both area databases. Verify summary LSAs at area boundaries.', 'verification'),
      step('mospf-5', 5, 'Test Connectivity',
        'Ping across areas to verify inter-area routing works.',
        ['ping 192.168.1.1 source 10.0.0.1', 'show ip route ospf'],
        'Routes from other areas show as O IA (inter-area) in the routing table.', 'verification'),
    ]),

  pb('ccna-snmp', 'SNMP v3 Configuration',
    'Configure SNMPv3 with authentication and privacy for secure network monitoring.',
    ['snmp', 'management'],
    [
      step('snmp-1', 1, 'Create SNMP v3 Group',
        'Define an SNMP group with security and access levels.',
        ['snmp-server group ADMINS v3 priv', 'snmp-server group READONLY v3 auth read MIBVIEW'],
        'priv = authentication + encryption. auth = authentication only. noauth = no security.'),
      step('snmp-2', 2, 'Create SNMP v3 User',
        'Add a user with authentication and privacy credentials.',
        ['snmp-server user admin ADMINS v3 auth sha Adm!nAuth2025 priv aes 128 Adm!nPriv2025'],
        'SHA for auth, AES for privacy. Use strong passphrases.'),
      step('snmp-3', 3, 'Set Contact and Location',
        'Add descriptive metadata for SNMP management.',
        ['snmp-server location DataCenter-A', 'snmp-server contact admin@cyberlab.local'],
        'Good practice for identifying devices in NMS.'),
      step('snmp-4', 4, 'Verify SNMP Configuration',
        'Confirm the SNMP server and user configuration.',
        ['show snmp user', 'show snmp group', 'show snmp'],
        'Verify user, group, security model, and access levels.', 'verification'),
    ]),

  pb('ccna-syslog', 'Syslog Configuration',
    'Configure a Cisco device to send log messages to a remote syslog server.',
    ['syslog', 'logging'],
    [
      step('slog-1', 1, 'Set Logging Severity Level',
        'Define which severity level messages to capture.',
        ['logging on', 'logging buffered 16384 debugging', 'logging console warnings'],
        'Severity levels 0-7 (emergencies to debugging). Higher number = more verbose.'),
      step('slog-2', 2, 'Configure Remote Syslog Server',
        'Send logs to an external syslog server.',
        ['logging host 10.0.0.5', 'logging trap informational', 'logging source-interface Loopback0'],
        'Use a loopback as source for consistent identification in logs.'),
      step('slog-3', 3, 'Add Timestamps to Logs',
        'Include timestamps in log messages for forensic analysis.',
        ['service timestamps log datetime msec localtime show-timezone'],
        'Millisecond precision timestamps essential for incident correlation.'),
      step('slog-4', 4, 'Verify Logging',
        'Confirm messages are being generated and forwarded.',
        ['show logging', 'show logging | include Syslog'],
        'Verify syslog server IP and trap level in show logging output.', 'verification'),
    ]),

  pb('ccna-bgp-basic', 'Basic BGP (eBGP)',
    'Configure external BGP between two autonomous systems and verify route exchange.',
    ['bgp', 'routing', 'wan'],
    [
      step('bgp-1', 1, 'Enable BGP Process',
        'Start the BGP process with your autonomous system number.',
        ['router bgp 65001'],
        'AS numbers 64512-65535 are private. 1-64511 are public/registered.'),
      step('bgp-2', 2, 'Configure eBGP Neighbor',
        'Add the external neighbor with their AS number.',
        ['neighbor 203.0.113.2 remote-as 65002', 'neighbor 203.0.113.2 description ISP-Upstream'],
        'eBGP forms between routers in different ASes. TCP port 179 must be reachable.'),
      step('bgp-3', 3, 'Advertise Network into BGP',
        'Inject a local network into BGP for propagation.',
        ['network 198.51.100.0 mask 255.255.255.0'],
        'The network must exist in the routing table first (static or connected).'),
      step('bgp-4', 4, 'Verify BGP Neighbor State',
        'Confirm the BGP session is in Established state.',
        ['show bgp summary', 'show ip bgp neighbors 203.0.113.2'],
        'Established state means BGP is up and exchanging routes.', 'verification'),
      step('bgp-5', 5, 'Verify BGP Routing Table',
        'Check BGP routes received from the neighbor.',
        ['show ip bgp', 'show ip route bgp'],
        'B = BGP route. > = best path selected. * = valid route.', 'verification'),
    ]),

]
