import type { Playbook, PlaybookStep } from './types'

function step(
  id: string, order: number, title: string, description: string,
  commands: string[], notes: string,
  stepType: PlaybookStep['stepType'] = 'command'
): PlaybookStep {
  return {
    id, order, title, description, category: 'enum',
    commands, notes, required: true, stepType,
  }
}

const NOW = '2025-01-01T00:00:00.000Z'

function pb(
  id: string, name: string, description: string, tags: string[],
  steps: PlaybookStep[]
): Playbook {
  return {
    id, name, description, category: 'ccna',
    tags: ['ccna', 'cisco', ...tags], version: '1.0',
    createdAt: NOW, updatedAt: NOW, isBuiltIn: true, steps,
  }
}

export const BUILTIN_CCNA_A: Playbook[] = [

  pb('ccna-ospf-single', 'OSPF Single Area (3 Routers)',
    'Configure OSPF in a single area across three routers and verify neighbor adjacencies.',
    ['ospf', 'routing'],
    [
      step('ospf1-1', 1, 'Configure Router Interfaces',
        'Assign IP addresses to the interfaces connecting the three routers.',
        ['interface GigabitEthernet0/0', 'ip address 10.0.12.1 255.255.255.0', 'no shutdown', 'exit'],
        'Repeat for each router interface. Use /30 or /24 subnets between routers.'),
      step('ospf1-2', 2, 'Enable OSPF Process',
        'Start the OSPF routing process and set the router ID.',
        ['router ospf 1', 'router-id 1.1.1.1', 'exit'],
        'Each router must have a unique router-id. Use a loopback for stability.'),
      step('ospf1-3', 3, 'Advertise Networks',
        'Add network statements to include all connected interfaces in OSPF area 0.',
        ['router ospf 1', 'network 10.0.12.0 0.0.0.255 area 0', 'network 192.168.1.0 0.0.0.255 area 0'],
        'Use wildcard masks (inverse of subnet mask). Area 0 is the backbone area.'),
      step('ospf1-4', 4, 'Verify OSPF Neighbors',
        'Check that all expected neighbor adjacencies are in FULL state.',
        ['show ip ospf neighbor', 'show ip ospf interface brief'],
        'State should be FULL for point-to-point links. DR/BDR elected on multi-access links.', 'verification'),
      step('ospf1-5', 5, 'Verify Routing Table',
        'Confirm OSPF routes (O) appear in the routing table.',
        ['show ip route ospf', 'show ip route'],
        'OSPF routes appear with "O" prefix. Verify all remote networks are reachable.', 'verification'),
      step('ospf1-6', 6, 'Test Connectivity',
        'Ping across the topology to confirm OSPF is forwarding traffic.',
        ['ping 10.0.23.2 source 192.168.1.1', 'traceroute 192.168.3.1'],
        'Use extended ping with source IP to test reachability through OSPF.', 'verification'),
    ]),

  pb('ccna-vlan', 'VLAN Configuration',
    'Create VLANs on a switch, assign access ports, and configure trunking.',
    ['vlan', 'switching'],
    [
      step('vlan-1', 1, 'Create VLANs',
        'Add VLAN IDs and descriptive names in the VLAN database.',
        ['vlan 10', 'name SALES', 'exit', 'vlan 20', 'name IT', 'exit', 'vlan 30', 'name MGMT', 'exit'],
        'VLANs 1, 1002-1005 are reserved. Use 2-4094 for custom VLANs.'),
      step('vlan-2', 2, 'Assign Access Ports',
        'Configure switch ports as access ports and assign them to VLANs.',
        ['interface FastEthernet0/1', 'switchport mode access', 'switchport access vlan 10', 'no shutdown'],
        'Access ports carry traffic for one VLAN only. Repeat for each host-facing port.'),
      step('vlan-3', 3, 'Configure Trunk Port',
        'Set the uplink as an 802.1Q trunk.',
        ['interface GigabitEthernet0/1', 'switchport mode trunk', 'switchport trunk encapsulation dot1q', 'switchport trunk allowed vlan 10,20,30'],
        'Trunk ports carry multiple VLANs tagged with 802.1Q headers.'),
      step('vlan-4', 4, 'Verify VLAN Database',
        'Confirm VLANs were created and ports assigned correctly.',
        ['show vlan brief', 'show interfaces trunk', 'show interfaces FastEthernet0/1 switchport'],
        'Active VLANs show in show vlan brief. Trunk interfaces listed in show interfaces trunk.', 'verification'),
    ]),

  pb('ccna-intervlan', 'Inter-VLAN Routing (Router-on-Stick)',
    'Enable routing between VLANs using 802.1Q subinterfaces on a router.',
    ['vlan', 'routing', 'subinterface'],
    [
      step('irv-1', 1, 'Set Physical Interface Up',
        'Bring up the router physical interface without an IP address.',
        ['interface GigabitEthernet0/0', 'no ip address', 'no shutdown', 'exit'],
        'The physical interface must be up; subinterfaces carry the IPs.'),
      step('irv-2', 2, 'Create Subinterface for VLAN 10',
        'Create a subinterface, set encapsulation, and assign gateway IP.',
        ['interface GigabitEthernet0/0.10', 'encapsulation dot1Q 10', 'ip address 192.168.10.1 255.255.255.0'],
        'The subinterface number typically matches the VLAN ID for clarity.'),
      step('irv-3', 3, 'Create Subinterface for VLAN 20',
        'Repeat for each additional VLAN.',
        ['interface GigabitEthernet0/0.20', 'encapsulation dot1Q 20', 'ip address 192.168.20.1 255.255.255.0'],
        'Each subinterface acts as the default gateway for its VLAN.'),
      step('irv-4', 4, 'Verify Subinterfaces',
        'Check that subinterfaces are up and have correct IPs.',
        ['show ip interface brief', 'show interfaces GigabitEthernet0/0.10'],
        'Both the physical interface and subinterfaces must show up/up.', 'verification'),
      step('irv-5', 5, 'Test Inter-VLAN Routing',
        'Ping from a host in VLAN 10 to a host in VLAN 20.',
        ['ping 192.168.20.10 source 192.168.10.10', 'show ip route connected'],
        'If ping fails check switch trunk config and encapsulation VLAN IDs match.', 'verification'),
    ]),

  pb('ccna-std-acl', 'Standard ACL',
    'Create and apply a numbered standard ACL to filter traffic based on source IP.',
    ['acl', 'security'],
    [
      step('sacl-1', 1, 'Create Standard ACL',
        'Define a numbered standard ACL permitting or denying source subnets.',
        ['access-list 10 deny 192.168.1.0 0.0.0.255', 'access-list 10 permit any'],
        'Standard ACLs (1-99, 1300-1999) filter on source IP only. Implicit deny any at end.'),
      step('sacl-2', 2, 'Apply ACL to Interface',
        'Bind the ACL inbound or outbound on the appropriate interface.',
        ['interface GigabitEthernet0/1', 'ip access-group 10 in', 'exit'],
        'Place standard ACLs closest to the destination. In = filters incoming traffic.'),
      step('sacl-3', 3, 'Verify ACL Configuration',
        'Review the ACL entries and their hit counters.',
        ['show access-lists 10', 'show ip interface GigabitEthernet0/1'],
        'Hit counts show how many packets matched each ACE.', 'verification'),
      step('sacl-4', 4, 'Test ACL Enforcement',
        'Generate traffic to verify the ACL permits/denies as expected.',
        ['ping 10.0.0.1 source 192.168.1.10', 'ping 10.0.0.1 source 10.1.1.1'],
        'Denied source should fail ping; permitted source should succeed.', 'verification'),
    ]),

  pb('ccna-ext-acl', 'Extended ACL',
    'Create and apply an extended ACL filtering on src/dst IP, protocol, and port.',
    ['acl', 'security', 'extended'],
    [
      step('eacl-1', 1, 'Create Extended ACL',
        'Define a numbered extended ACL with source, destination, protocol, and port matching.',
        ['access-list 100 deny tcp 192.168.1.0 0.0.0.255 any eq 80', 'access-list 100 deny tcp 192.168.1.0 0.0.0.255 any eq 443', 'access-list 100 permit ip any any'],
        'Extended ACLs (100-199, 2000-2699) filter on src/dst IP, protocol, and port.'),
      step('eacl-2', 2, 'Apply ACL to Interface',
        'Bind the extended ACL close to the source for efficiency.',
        ['interface GigabitEthernet0/0', 'ip access-group 100 in', 'exit'],
        'Extended ACLs should be placed close to the source to stop traffic early.'),
      step('eacl-3', 3, 'Verify ACL Entries',
        'Check the ACL rules and hit counters.',
        ['show access-lists 100', 'show running-config | section access-list'],
        'Verify permit ip any any is last to avoid blocking all traffic.', 'verification'),
      step('eacl-4', 4, 'Test Protocol Filtering',
        'Test that blocked protocol is denied and other traffic passes.',
        ['telnet 10.0.0.1 80', 'ping 10.0.0.1'],
        'HTTP should be blocked while ICMP ping is permitted.', 'verification'),
    ]),

  pb('ccna-eigrp', 'EIGRP Configuration',
    'Configure EIGRP routing on multiple routers and verify neighbor relationships.',
    ['eigrp', 'routing'],
    [
      step('eigrp-1', 1, 'Enable EIGRP Process',
        'Start EIGRP with an autonomous system number matching on all routers.',
        ['router eigrp 100', 'eigrp router-id 1.1.1.1', 'no auto-summary'],
        'The AS number must match on all routers for neighbors to form. Disable auto-summary.'),
      step('eigrp-2', 2, 'Advertise Networks',
        'Add network statements for all directly connected networks.',
        ['router eigrp 100', 'network 10.0.12.0 0.0.0.3', 'network 192.168.1.0 0.0.0.255'],
        'Wildcard masks are optional; classful network statement also works.'),
      step('eigrp-3', 3, 'Verify EIGRP Neighbors',
        'Confirm neighbor adjacencies are formed.',
        ['show ip eigrp neighbors', 'show ip eigrp interfaces'],
        'Uptime and queue count visible. H column shows hold timer.', 'verification'),
      step('eigrp-4', 4, 'Verify Routing Table',
        'Check that EIGRP routes (D) appear in the routing table.',
        ['show ip route eigrp', 'show ip eigrp topology'],
        'D = EIGRP route. Topology table shows successors and feasible successors.', 'verification'),
    ]),

  pb('ccna-ripv2', 'RIP v2 Configuration',
    'Configure RIPv2 on routers with VLSM support and verify route propagation.',
    ['rip', 'routing'],
    [
      step('rip-1', 1, 'Enable RIP and Set Version 2',
        'Start the RIP process and specify version 2 for VLSM support.',
        ['router rip', 'version 2', 'no auto-summary'],
        'RIP v1 is classful. Always use v2 for VLSM/CIDR support. Disable auto-summary.'),
      step('rip-2', 2, 'Advertise Networks',
        'Add classful network statements for directly connected networks.',
        ['router rip', 'network 10.0.0.0', 'network 192.168.1.0'],
        'RIP uses classful network statements. The process activates on matching interfaces.'),
      step('rip-3', 3, 'Verify RIP Routes',
        'Check the routing table for RIP routes.',
        ['show ip route rip', 'show ip rip database'],
        'R = RIP route. [120/X] shows admin distance 120 and hop count.', 'verification'),
      step('rip-4', 4, 'Debug RIP Updates',
        'Temporarily enable RIP debugging to see update messages.',
        ['debug ip rip', 'undebug all'],
        'Shows incoming and outgoing RIP updates. Always undebug when done!', 'verification'),
    ]),

  pb('ccna-nat', 'NAT/PAT Configuration',
    'Configure NAT overload (PAT) to translate private addresses to a single public IP.',
    ['nat', 'pat'],
    [
      step('nat-1', 1, 'Define Inside/Outside Interfaces',
        'Mark the LAN-facing interface as inside and the WAN-facing as outside.',
        ['interface GigabitEthernet0/0', 'ip nat inside', 'exit', 'interface GigabitEthernet0/1', 'ip nat outside', 'exit'],
        'NAT translates between inside-local and outside-global addresses.'),
      step('nat-2', 2, 'Create ACL for Inside Hosts',
        'Define which source addresses should be translated.',
        ['access-list 1 permit 192.168.0.0 0.0.255.255'],
        'This ACL selects traffic eligible for NAT translation.'),
      step('nat-3', 3, 'Configure NAT Overload (PAT)',
        'Enable NAT overload using the outside interface IP.',
        ['ip nat inside source list 1 interface GigabitEthernet0/1 overload'],
        'Overload keyword enables PAT — many-to-one using port numbers.'),
      step('nat-4', 4, 'Verify NAT Translations',
        'Generate traffic and inspect the NAT translation table.',
        ['show ip nat translations', 'show ip nat statistics'],
        'Translations show inside local, inside global, outside local, outside global.', 'verification'),
      step('nat-5', 5, 'Clear and Re-test',
        'Clear the NAT table and verify translations rebuild on new traffic.',
        ['clear ip nat translation *', 'ping 8.8.8.8', 'show ip nat translations'],
        'Confirm translations are created after clearing the table.', 'verification'),
    ]),

  pb('ccna-dhcp', 'DHCP Server Configuration',
    'Configure a Cisco router as a DHCP server for a LAN segment.',
    ['dhcp', 'ip-services'],
    [
      step('dhcp-1', 1, 'Exclude Static Addresses',
        'Reserve IP addresses for routers, servers, and printers.',
        ['ip dhcp excluded-address 192.168.1.1 192.168.1.20'],
        'Always exclude before creating the pool to prevent conflicts.'),
      step('dhcp-2', 2, 'Create DHCP Pool',
        'Define the pool name, network, default gateway, and DNS server.',
        ['ip dhcp pool LAN', 'network 192.168.1.0 255.255.255.0', 'default-router 192.168.1.1', 'dns-server 8.8.8.8 8.8.4.4', 'lease 7'],
        'Lease time is in days. Domain-name is optional but useful.'),
      step('dhcp-3', 3, 'Verify DHCP Bindings',
        'Check which IP addresses have been assigned to clients.',
        ['show ip dhcp binding', 'show ip dhcp pool', 'show ip dhcp conflict'],
        'Bindings show MAC address and lease expiry. Conflicts show rejected addresses.', 'verification'),
      step('dhcp-4', 4, 'Test Client Address Assignment',
        'Verify a client can obtain an IP address from the DHCP server.',
        ['debug ip dhcp server events', 'undebug all'],
        'Debug shows DISCOVER, OFFER, REQUEST, ACK sequence.', 'verification'),
    ]),

  pb('ccna-ssh', 'SSH Hardening',
    'Harden device access by configuring SSH and disabling Telnet on VTY lines.',
    ['ssh', 'security'],
    [
      step('ssh-1', 1, 'Set Hostname and Domain Name',
        'A hostname and domain name are required to generate RSA keys.',
        ['hostname SW1', 'ip domain-name cyberlab.local'],
        'Without a domain name, crypto key generate will fail.'),
      step('ssh-2', 2, 'Generate RSA Key Pair',
        'Create the RSA keys used for SSH encryption.',
        ['crypto key generate rsa modulus 2048'],
        'Use at least 1024 bits; 2048 is recommended. Keys enable SSH v2.'),
      step('ssh-3', 3, 'Create Local User',
        'Add a privileged local account for SSH login.',
        ['username admin privilege 15 secret CyberL@b2025!'],
        'Use secret not password — secret stores a hashed value.'),
      step('ssh-4', 4, 'Configure VTY for SSH Only',
        'Restrict VTY lines to SSH and set local authentication.',
        ['line vty 0 4', 'transport input ssh', 'login local', 'exec-timeout 5 0', 'exit'],
        'transport input ssh blocks Telnet. exec-timeout auto-disconnects idle sessions.'),
      step('ssh-5', 5, 'Set SSH Version 2 and Verify',
        'Force SSH version 2 and confirm the configuration.',
        ['ip ssh version 2', 'ip ssh time-out 60', 'ip ssh authentication-retries 3', 'show ip ssh', 'show line vty 0 4'],
        'SSH v2 required for security compliance. Confirm VTY shows ssh only.', 'verification'),
    ]),
]
