declare const api: {
    getConfig: () => Promise<any>;
    saveConfig: (cfg: unknown) => Promise<any>;
    getOutputDir: () => Promise<any>;
    saveApiKey: (key: string) => Promise<any>;
    testApiKey: (key: string) => Promise<any>;
    hasApiKey: () => Promise<any>;
    claudeChat: (payload: unknown) => Promise<any>;
    ollamaChat: (payload: unknown) => Promise<any>;
    ollamaListModels: (endpoint?: string) => Promise<any>;
    takeScreenshot: () => Promise<any>;
    saveScreenshot: (data: unknown) => Promise<any>;
    pushToReconDesk: (data: unknown) => Promise<any>;
    getReconDeskTarget: (data: unknown) => Promise<any>;
    saveSession: (data: unknown) => Promise<any>;
    loadSession: (id: string) => Promise<any>;
    listSessions: () => Promise<any>;
    deleteSession: (id: string) => Promise<any>;
    saveWriteup: (data: unknown) => Promise<any>;
    exportPDF: (data: unknown) => Promise<any>;
    scanVault: (vaultPath: string) => Promise<any>;
    pickFolder: () => Promise<any>;
    checkVPN: () => Promise<any>;
    checkUpdate: () => Promise<any>;
    syncHTB: (apiKey: string) => Promise<any>;
    syncTHM: (username: string) => Promise<any>;
    saveHtbToken: (token: string) => Promise<any>;
    testHtbToken: (token?: string) => Promise<any>;
    clearHtbToken: () => Promise<any>;
    hasHtbToken: () => Promise<any>;
    fetchHtbStats: () => Promise<any>;
    saveThmToken: (payload: {
        token: string;
        username?: string;
    }) => Promise<any>;
    testThmToken: (payload?: {
        token?: string;
        username?: string;
    }) => Promise<any>;
    clearThmToken: () => Promise<any>;
    hasThmToken: () => Promise<any>;
    fetchThmStats: () => Promise<any>;
    setActiveLab: (payload: {
        name: string | null;
        platform: string;
        ip?: string;
    }) => Promise<any>;
    updateLauncherStatus: (status: unknown) => Promise<any>;
    saveProgress: (data: unknown) => Promise<any>;
    loadProgress: () => Promise<any>;
    saveLabTracker: (data: unknown) => Promise<any>;
    loadLabTracker: () => Promise<any>;
    saveSnippets: (data: unknown) => Promise<any>;
    loadSnippets: () => Promise<any>;
    saveAnnotatedScreenshot: (data: unknown) => Promise<any>;
    saveKnowledgeBase: (data: unknown) => Promise<any>;
    loadKnowledgeBase: () => Promise<any>;
    saveLabReviews: (data: unknown) => Promise<any>;
    loadLabReviews: () => Promise<any>;
    exportHtml: (data: unknown) => Promise<any>;
    openExternal: (url: string) => Promise<any>;
    getVersion: () => Promise<any>;
    getPlatform: () => Promise<any>;
    onUpdateAvailable: (cb: (data: unknown) => void) => void;
    onFocusWindow: (cb: () => void) => void;
    onAutosaveTick: (cb: () => void) => () => Electron.IpcRenderer;
    onVpnStatus: (cb: (data: unknown) => void) => () => Electron.IpcRenderer;
    onPendingAction: (cb: (action: string) => void) => () => Electron.IpcRenderer;
    ecosystemEmit: (appName: string, eventType: string, data: unknown) => Promise<any>;
    incrementFlags: (count?: number) => Promise<any>;
    updateOperatorProfile: (updates: object) => Promise<any>;
    completeLab: (opts: {
        platform: string;
        labType: string;
    }) => Promise<any>;
    startLab: (opts: {
        name: string;
        platform: string;
        targetIP?: string;
        findingsCount?: number;
    }) => Promise<any>;
    updateLabFindings: (opts: {
        findingsCount: number;
    }) => Promise<any>;
    endLab: () => Promise<any>;
    removeAllListeners: (channel: string) => Electron.IpcRenderer;
};
export type CyberLabAPI = typeof api;
export {};
