import { useState, useEffect, useRef } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { useStore } from '../store';
import CollabExport from './writeup/CollabExport';
import DifficultyRatingModal from './writeup/DifficultyRatingModal';

// ── Templates ─────────────────────────────────────────────────────────────────

const TEMPLATES: Record<string, string> = {
  default: `# {LAB_NAME} — {PLATFORM} ({DIFFICULTY})

**Date:** {DATE}
**Duration:** {DURATION}
**Hints Used:** {HINTS}

---

## Enumeration

### Port Scan

\`\`\`
\`\`\`

### Service Enumeration



## Foothold



## Privilege Escalation



## Post-Exploitation



## Flags

| Flag | Value |
|------|-------|
| User | |
| Root | |

---

## Lessons Learned



## Tools Used

`,
  Web: `# {LAB_NAME} — {PLATFORM} ({DIFFICULTY})

**Date:** {DATE}  **Duration:** {DURATION}

## Recon

### Technology Stack


### Directory Enumeration

\`\`\`
\`\`\`

## Enumeration



## Exploitation

### Vulnerability Found


### Exploit Steps


## Post-Exploitation



## Flags

{FLAGS}

## Tools Used

`,
  Pwn: `# {LAB_NAME} — {PLATFORM} ({DIFFICULTY})

**Date:** {DATE}

## Binary Analysis

### Protections


### Vulnerable Functions


## Vulnerability



## Exploit Development

\`\`\`python
from pwn import *
\`\`\`

## Flag

{FLAGS}
`,
  Crypto: `# {LAB_NAME} — Crypto Challenge

**Date:** {DATE}

## Cipher/Encoding Identification



## Analysis



## Solution

\`\`\`python
\`\`\`

## Flag

{FLAGS}
`,
  Forensics: `# {LAB_NAME} — Forensics Challenge

**Date:** {DATE}

## File Analysis

### File Type


### Metadata


## Investigation



## Flag

{FLAGS}
`,
  Rev: `# {LAB_NAME} — Reverse Engineering

**Date:** {DATE}

## Binary Analysis

### Static Analysis


### Dynamic Analysis


## Key Algorithm / Logic



## Solution



## Flag

{FLAGS}
`,
  OSINT: `# {LAB_NAME} — OSINT Challenge

**Date:** {DATE}

## Initial Leads



## Passive Recon



## Active Investigation



## Findings



## Flag

{FLAGS}
`,
};

// ── CVE / MITRE auto-tagging ─────────────────────────────────────────────────

const CVE_RE = /CVE-\d{4}-\d{4,}/gi;
const MITRE_RE = /T\d{4}(?:\.\d{3})?/g;

interface Tag { type: 'cve' | 'mitre'; value: string; url: string; }

function extractTags(text: string): Tag[] {
  const tags: Tag[] = [];
  const cves = text.match(CVE_RE) || [];
  const mitres = text.match(MITRE_RE) || [];
  const seenCve = new Set<string>();
  const seenMitre = new Set<string>();
  for (const c of cves) {
    const u = c.toUpperCase();
    if (!seenCve.has(u)) {
      seenCve.add(u);
      tags.push({ type: 'cve', value: u, url: `https://nvd.nist.gov/vuln/detail/${u}` });
    }
  }
  for (const m of mitres) {
    if (!seenMitre.has(m)) {
      seenMitre.add(m);
      tags.push({ type: 'mitre', value: m, url: `https://attack.mitre.org/techniques/${m.replace('.', '/')}` });
    }
  }
  return tags;
}

// ── HTML export ───────────────────────────────────────────────────────────────

function buildHtmlExport(content: string, labName: string, platform: string, flagCount: number): string {
  const escaped = content
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${labName} — CyberLab Writeup</title>
<style>
body{background:#0a0a0f;color:#e6edf3;font-family:Inter,sans-serif;padding:40px;max-width:860px;margin:0 auto}
h1{color:#b44fff;border-bottom:1px solid #2a3347;padding-bottom:8px}
h2{color:#4a9eff;margin-top:28px}
code,pre{font-family:'JetBrains Mono',monospace;background:#0f1117;padding:2px 6px;border-radius:4px;color:#3fb950}
.meta{color:#8b949e;font-size:13px;margin-bottom:24px}
.flag-count{color:#3fb950;font-weight:bold}
</style>
</head>
<body>
<h1>${labName} — ${platform} Writeup</h1>
<div class="meta">Generated by CyberLab Companion &nbsp;·&nbsp; Flags: <span class="flag-count">${flagCount}</span></div>
<div>${escaped}</div>
</body>
</html>`;
}

// ── Component ─────────────────────────────────────────────────────────────────

function buildContent(session: { labName: string; platform: string; difficulty: string; timer?: { elapsed?: number }; hintsUsed?: number; labType?: string; findings?: { flags?: Array<{ value: string }> } }, templateKey: string): string {
  const elapsed = session.timer?.elapsed ?? 0;
  const h = Math.floor(elapsed / 3600);
  const m = Math.floor((elapsed % 3600) / 60);
  const duration = elapsed > 0 ? `${h}h ${m}m` : '';
  const flagLines = (session.findings?.flags ?? []).map(f => `- \`${f.value}\``).join('\n') || '- (none)';

  const tplKey = Object.keys(TEMPLATES).find(k =>
    k !== 'default' && (session.labType || '').toLowerCase().includes(k.toLowerCase())
  ) || templateKey || 'default';

  return (TEMPLATES[tplKey] || TEMPLATES['default'])
    .replace(/\{LAB_NAME\}/g, session.labName || 'Lab')
    .replace(/\{PLATFORM\}/g, session.platform || 'HTB')
    .replace(/\{DIFFICULTY\}/g, session.difficulty || 'Medium')
    .replace(/\{DATE\}/g, new Date().toLocaleDateString())
    .replace(/\{DURATION\}/g, duration)
    .replace(/\{HINTS\}/g, String(session.hintsUsed || 0))
    .replace(/\{FLAGS\}/g, flagLines);
}

export default function WriteupPanel() {
  const { tabs, activeTabId, config, updateSession } = useStore();
  const activeTab = tabs.find(t => t.id === activeTabId);
  const session = activeTab?.session;

  const [templateKey, setTemplateKey] = useState('default');
  const [content, setContent] = useState(() => session ? buildContent(session, 'default') : TEMPLATES['default']);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [tags, setTags] = useState<Tag[]>([]);
  const [showCollab, setShowCollab] = useState(false);
  const [showRating, setShowRating] = useState(false);
  const autoSaveRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Re-generate when session or template changes
  useEffect(() => {
    if (session) setContent(buildContent(session, templateKey));
  }, [session?.id, templateKey]);

  // Auto-extract CVE/MITRE tags
  useEffect(() => {
    setTags(extractTags(content));
  }, [content]);

  // Persist writeupContent to session (debounced 2s) so GhostVault auto-save can read it
  useEffect(() => {
    if (!activeTabId || !session) return;
    const t = setTimeout(() => {
      updateSession(activeTabId, { writeupContent: content });
    }, 2000);
    return () => clearTimeout(t);
  }, [content, activeTabId]);

  // Auto-save to GhostVault every 2 minutes
  useEffect(() => {
    if (!session || !config?.obsidianVault) return;
    if (autoSaveRef.current) clearTimeout(autoSaveRef.current);
    autoSaveRef.current = setTimeout(async () => {
      try {
        await window.electronAPI.saveWriteup({
          content,
          labName: session.labName,
          platform: session.platform,
          vaultPath: config.obsidianVault,
        });
      } catch {}
    }, 120000);
    return () => { if (autoSaveRef.current) clearTimeout(autoSaveRef.current); };
  }, [content]);

  async function saveWriteup() {
    if (!session) return;
    setSaving(true);
    try {
      const result = await window.electronAPI.saveWriteup({
        content,
        labName: session.labName,
        platform: session.platform,
        vaultPath: config?.obsidianVault || '',
      }) as { success: boolean; error?: string };
      if (result?.success) {
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
      }
    } catch {}
    finally { setSaving(false); }
  }

  async function exportPdf() {
    if (!session) return;
    try { await window.electronAPI.exportPDF({ labName: session.labName, content }); } catch {}
  }

  async function exportHtml() {
    if (!session) return;
    const html = buildHtmlExport(content, session.labName, session.platform, session.findings.flags.length);
    try {
      await navigator.clipboard.writeText(html);
    } catch {}
    // Optionally save to disk via saveWriteup with .html extension — just copy for now
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${session.labName}-writeup.html`; a.click();
    URL.revokeObjectURL(url);
  }

  async function openExternal(url: string) {
    try { await window.electronAPI.openExternal(url); } catch {}
  }

  return (
    <div className="flex flex-col h-full">
      {/* Toolbar */}
      <div className="flex items-center gap-2 px-4 py-2 flex-shrink-0"
        style={{ borderBottom: '1px solid var(--border)', background: 'var(--bg2)' }}>
        <span className="text-xs font-semibold" style={{ color: 'var(--text-dim)' }}>Writeup</span>
        {session && <span className="text-xs" style={{ color: 'var(--text-muted)' }}>— {session.labName}</span>}

        {/* Template selector */}
        <select
          value={templateKey}
          onChange={e => setTemplateKey(e.target.value)}
          className="text-[10px] ml-2"
          style={{ width: 'auto', padding: '2px 6px' }}
        >
          <option value="default">Default Template</option>
          {Object.keys(TEMPLATES).filter(k => k !== 'default').map(k => (
            <option key={k} value={k}>{k}</option>
          ))}
        </select>

        <div className="flex-1" />
        <button className="btn-ghost text-xs px-2 py-1" onClick={() => setShowCollab(true)}>Share</button>
        <button className="btn-ghost text-xs px-2 py-1" onClick={() => setShowRating(true)}>Rate</button>
        <button className="btn-ghost text-xs px-2 py-1" onClick={exportHtml}>HTML</button>
        <button className="btn-ghost text-xs px-2 py-1" onClick={exportPdf}>PDF</button>
        <button className="btn-accent text-xs px-3 py-1.5" onClick={saveWriteup} disabled={saving}>
          {saving ? 'Saving...' : saved ? 'Saved!' : 'Save'}
        </button>
      </div>

      {/* CVE/MITRE tags */}
      {tags.length > 0 && (
        <div className="flex items-center gap-1.5 px-4 py-1.5 flex-shrink-0 flex-wrap"
          style={{ borderBottom: '1px solid var(--border)', background: 'var(--bg3)' }}>
          <span className="text-[10px]" style={{ color: 'var(--text-muted)' }}>Detected:</span>
          {tags.map(tag => (
            <button
              key={tag.value}
              className="text-[10px] px-1.5 py-0.5 rounded transition-colors"
              style={{
                background: tag.type === 'cve' ? '#f8514922' : '#b44fff22',
                color: tag.type === 'cve' ? '#f85149' : '#b44fff',
                border: `1px solid ${tag.type === 'cve' ? '#f8514944' : '#b44fff44'}`,
              }}
              onClick={() => openExternal(tag.url)}
              title={`Open ${tag.value} in browser`}
            >
              {tag.value}
            </button>
          ))}
        </div>
      )}

      {/* Editor */}
      <textarea
        value={content}
        onChange={e => setContent(e.target.value)}
        className="flex-1 resize-none p-4 font-mono text-xs leading-relaxed selectable"
        style={{ background: 'var(--bg)', border: 'none', outline: 'none', color: 'var(--text)' }}
        spellCheck={false}
      />

      {/* Footer stats */}
      {session && (
        <div className="flex items-center gap-4 px-4 py-1.5 flex-shrink-0 text-xs"
          style={{ borderTop: '1px solid var(--border)', background: 'var(--bg2)', color: 'var(--text-muted)' }}>
          <span>{content.split('\n').length} lines</span>
          {session.timer?.elapsed ? (
            <span className="font-mono">
              {Math.floor(session.timer.elapsed / 3600)}h {Math.floor((session.timer.elapsed % 3600) / 60)}m
            </span>
          ) : null}
          {(session.hintsUsed || 0) > 0 && (
            <span style={{ color: 'var(--warning)' }}>Hints: {session.hintsUsed}</span>
          )}
          {session.findings.flags.length > 0 && (
            <span style={{ color: 'var(--success)' }}>Flags: {session.findings.flags.length}</span>
          )}
          {tags.length > 0 && (
            <span style={{ color: '#b44fff' }}>{tags.length} tag{tags.length !== 1 ? 's' : ''} detected</span>
          )}
          <div className="flex-1" />
          {config?.obsidianVault && (
            <span style={{ color: 'var(--text-muted)', opacity: 0.5 }}>Auto-save: 2min</span>
          )}
        </div>
      )}

      {/* Modals */}
      <AnimatePresence>
        {showCollab && session && (
          <CollabExport session={session} onClose={() => setShowCollab(false)} />
        )}
      </AnimatePresence>

      <AnimatePresence>
        {showRating && session && (
          <DifficultyRatingModal
            session={session}
            onSave={(rating, notes) => {
              // Store rating in localStorage
              try {
                const key = `cyberlab-rating-${session.id}`;
                localStorage.setItem(key, JSON.stringify({ rating, notes, savedAt: new Date().toISOString() }));
              } catch {}
              setShowRating(false);
            }}
            onCancel={() => setShowRating(false)}
          />
        )}
      </AnimatePresence>
    </div>
  );
}
